services:
  postgres:
    image: postgres:16
    container_name: cron_booking_postgres
    restart: always
    environment:
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_pass
      POSTGRES_DB: booking_db
    ports:
      - "5435:5432"
    volumes:
      - cron_booking_postgres_data:/var/lib/postgresql/data

  dbgate:
    image: dbgate/dbgate:latest
    container_name: cron_booking_dbgate
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:3000"
    environment:
      - DBGATE_STORAGE=local
      - DBGATE_STORAGE_PATH=/dbgate-data
    volumes:
      - dbgate_data:/dbgate-data

volumes:
  cron_booking_postgres_data:
  dbgate_data: